import { getLogSnapshot } from "@/lib/agent-client";

export default async function LogsPage() {
	const snapshot = await getLogSnapshot(25);
	const totalLines = snapshot.sections.reduce((count, section) => count + section.lines.length, 0);
	const activeSources = snapshot.sections.filter((section) => section.lines.length > 0).length;
	const journalNotice = snapshot.sections.find((section) => section.id === "control-plane")?.notice;

	return (
		<div style={{ display: "grid", gap: 24 }}>
			<section style={{ display: "grid", gap: 16, gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))" }}>
				<MetricCard label="Sources" value={`${activeSources}/${snapshot.sections.length}`} detail="Sources currently returning log lines" />
				<MetricCard label="Visible lines" value={String(totalLines)} detail="Combined lines across journal and file tails" mono />
				<MetricCard label="Journal" value={journalNotice ? "attention" : "live"} detail={journalNotice || "Control-plane journal lines are flowing"} />
				<MetricCard label="Refreshed" value={formatTime(snapshot.generated_at)} detail="Snapshot generated by the agent on demand" mono />
			</section>

			<section className="aegis-card" style={{ padding: 24, display: "grid", gap: 10 }}>
				<span className="aegis-badge">Logs</span>
				<h1 style={{ margin: 0, fontSize: 32 }}>Unified log surface</h1>
				<p style={{ margin: 0, color: "var(--foreground-muted)", lineHeight: 1.7, maxWidth: 860 }}>
					Recent control-plane journal lines, reverse-proxy access output, and installer traces stay in one place so operators can diagnose deploy and runtime failures without dropping back to the shell first.
				</p>
			</section>

			<section style={{ display: "grid", gap: 16 }}>
				{snapshot.sections.map((section) => (
					<article key={section.id} className="aegis-card" style={{ padding: 20, display: "grid", gap: 16 }}>
						<div style={{ display: "flex", justifyContent: "space-between", gap: 16, alignItems: "flex-start", flexWrap: "wrap" }}>
							<div style={{ display: "grid", gap: 6 }}>
								<div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
									<span className="aegis-badge">{section.kind}</span>
									<span className="aegis-badge">{section.lines.length} lines</span>
								</div>
								<h2 style={{ margin: 0, fontSize: 22 }}>{section.label}</h2>
								<div style={{ color: "var(--foreground-muted)", lineHeight: 1.6 }}>{section.description}</div>
							</div>
							<span className="aegis-badge">{section.id}</span>
						</div>

						{section.notice ? (
							<div className="aegis-card" style={{ padding: 14, color: "var(--foreground-muted)" }}>{section.notice}</div>
						) : null}

						{section.lines.length === 0 ? (
							<div style={{ color: "var(--foreground-muted)" }}>No log lines are currently available from this source.</div>
						) : (
							<div style={{ display: "grid", gap: 12 }}>
								{section.lines.map((line, index) => (
									<article key={`${section.id}-${index}`} className="aegis-card" style={{ padding: 16, display: "grid", gap: 10 }}>
										<div style={{ display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center" }}>
											{line.timestamp ? <span className="aegis-badge">{formatTime(line.timestamp)}</span> : null}
											{line.source ? <span className="aegis-badge">{line.source}</span> : null}
											{line.level ? <span className="aegis-badge">{line.level}</span> : null}
										</div>
										<div style={{ fontWeight: 600, lineHeight: 1.6 }}>{line.summary}</div>
										<pre className="aegis-mono" style={rawStyle}>{truncate(line.raw, 800)}</pre>
									</article>
								))}
							</div>
						)}
					</article>
				))}
			</section>
		</div>
	);
}

const rawStyle: React.CSSProperties = {
	margin: 0,
	padding: 14,
	borderRadius: 12,
	border: "1px solid var(--hairline)",
	background: "var(--surface-alt)",
	color: "var(--foreground-muted)",
	fontSize: 12,
	lineHeight: 1.5,
	overflowX: "auto",
	whiteSpace: "pre-wrap",
	wordBreak: "break-word",
};

function MetricCard({ label, value, detail, mono = false }: { label: string; value: string; detail: string; mono?: boolean }) {
	return (
		<article className="aegis-card" style={{ padding: 20 }}>
			<div className="aegis-badge">{label}</div>
			<h2 className={mono ? "aegis-mono" : undefined} style={{ margin: "14px 0 6px", fontSize: 28 }}>{value}</h2>
			<div style={{ color: "var(--foreground-muted)", lineHeight: 1.6 }}>{detail}</div>
		</article>
	);
}

function formatTime(value: string) {
	const date = new Date(value);
	if (Number.isNaN(date.getTime())) {
		return value;
	}
	return new Intl.DateTimeFormat("en", {
		dateStyle: "medium",
		timeStyle: "short",
	}).format(date);
}

function truncate(value: string, maxLength: number) {
	if (value.length <= maxLength) {
		return value;
	}
	return `${value.slice(0, maxLength)}...`;
}